name: Broadcast
version: "1.0.0"
author: applqpak
api: ["1.0.0"]
main: applqpak.Broadcast.Main
description: A simple plugin that allows you to broadcast a message via command.
commands:
  broadcast:
    description: Core Broadcast command.
    usage: "/broadcast < message >"
    aliases: ["bc"]
    permission: broadcast.command
permissions:
  broadcast.command:
    default: op
